import React, { createContext, useState, useContext } from 'react';

const translations = {
  es: {
    // Categorías de Navegación
    gestion: 'Gestión',
    comercial: 'Comercial',
    inventario: 'Inventario',
    contabilidad: 'Contabilidad',

    // Elementos del menú
    dashboard: 'Dashboard',
    alertas: 'Alertas',
    calendario: 'Calendario',
    clientes: 'Clientes',
    ventas: 'Ventas (TPV)',
    consentimientos: 'Consentimientos',
    cabinas: 'Cabinas & Alquileres',
    empleados: 'Empleados',
    comunicaciones: 'Comunicaciones',
    leads: 'Leads',
    proyectos: 'Proyectos',
    presupuestos: 'Presupuestos',
    seguimientos: 'Seguimientos',
    pipeline: 'Pipeline (Kanban)',
    insights: 'Insights Comercial',
    tintas: 'Tintas',
    agujas: 'Agujas',
    piercing: 'Piercing',
    materiales: 'Materiales',
    estadisticas: 'Estadísticas',
    gastos: 'Gastos',
    ingresos: 'Ingresos',
    recuento_diario: 'Recuento Diario',
    mi_liquidacion: 'Mi Liquidación',
    liq_estudio: 'Liq. Estudio',
    recibos: 'Recibos',
    configuracion: 'Configuración',
    cerrar_sesion: 'Cerrar sesión',
    panel_superadmin: 'Panel SuperAdmin',

    // Dashboard
    buenos_dias: 'Buenos días',
    buenas_tardes: 'Buenas tardes',
    buenas_noches: 'Buenas noches',
    accesos_rapidos: 'Accesos Rápidos',
    citas_de_hoy: 'Citas de hoy',
    ventas_del_mes: 'Ventas del mes',
    gastos_del_mes: 'Gastos del mes',
    beneficio_del_mes: 'Beneficio del mes',
    pendientes: 'Pendientes',
    alertas_pendientes: 'alertas',
    leads_activos: 'Leads Activos',
    en_seguimiento: 'En seguimiento',
    proyectos_diseno: 'Proyectos',
    en_diseno: 'En diseño / curso',
    presupuestos_aceptados: 'Presupuestos',
    aceptados: 'Aceptados',
    conversion_crm: 'Conversión CRM',
    leads_a_clientes: 'Leads a Clientes',
    nueva_cita: 'Nueva Cita',
    programa_calendario: 'Programa en el calendario',
    anadir_cliente: 'Añadir Cliente',
    registra_perfil: 'Registra un nuevo perfil',
    ver_inventario: 'Ver Inventario',
    consulta_productos: 'Consulta tus productos',
    ajusta_estudio: 'Ajusta tu estudio',
    ir: 'Ir →',
    no_hay_citas_hoy: 'No hay citas programadas para hoy',
    stock_bajo_en: 'Stock bajo en',
    con_no_shows: 'con 3+ no-shows',
    ausencias_semana: 'Ausencias esta semana',

    // Clientes
    clientes_titulo: 'Clientes',
    nuevo_cliente: 'Nuevo cliente',
    duplicados: 'Duplicados',
    buscar_cliente_placeholder: 'Buscar por nombre, apellidos o email...',
    todos: 'Todos',
    conflictivos: '⚠ Conflictivos',
    flexibles: 'Flexibles',
    sin_resultados: 'No se encontraron resultados',
    no_hay_clientes: 'No hay clientes registrados',
    primer_apellido: 'Primer apellido',
    segundo_apellido: 'Segundo apellido',
    fecha_nacimiento: 'Fecha de nacimiento',
    sexo: 'Sexo',

    // Calendario & Citas
    calendario_titulo: 'Calendario de Citas',
    mes: 'Mes',
    semana: 'Semana',
    dia: 'Día',
    hoy: 'Hoy',

    // TPV & Ventas
    ventas_tpv_titulo: 'Terminal Punto de Venta (TPV)',
    nueva_venta: 'Nueva Venta',
    cobrar: 'Cobrar',
    ticket: 'Ticket',
    carrito_vacio: 'El carrito está vacío',
    subtotal: 'Subtotal',
    descuento: 'Descuento',
    metodo_pago: 'Método de Pago',
    efectivo: 'Efectivo',
    tarjeta: 'Tarjeta',
    bizum: 'Bizum',
    imprimir_ticket: 'Imprimir Ticket',
    finalizar_venta: 'Finalizar Venta',

    // Inventario (Tintas, Agujas, Piercing, Materiales)
    tintas_titulo: 'Gestión de Tintas',
    agujas_titulo: 'Gestión de Agujas y Cartuchos',
    piercing_titulo: 'Gestión de Piercing y Joyería',
    materiales_titulo: 'Materiales e Insumos',
    stock_actual: 'Stock Actual',
    stock_minimo: 'Stock Mínimo',
    lote: 'Lote',
    caducidad: 'Fecha de Caducidad',
    proveedor: 'Proveedor',
    precio_compra: 'Precio Compra',
    precio_venta: 'Precio Venta',
    marca: 'Marca',
    modelo: 'Modelo',
    tipo: 'Tipo',

    // Cabinas & Empleados
    cabinas_titulo: 'Cabinas y Espacios de Trabajo',
    nueva_cabina: 'Nueva Cabina',
    empleados_titulo: 'Gestión de Empleados y Artistas',
    nuevo_empleado: 'Nuevo Empleado',
    comision: 'Comisión (%)',
    especialidad: 'Especialidad',

    // CRM
    leads_titulo: 'Gestión de Leads',
    nuevo_lead: 'Nuevo Lead',
    proyectos_titulo: 'Proyectos de Diseño',
    nuevo_proyecto: 'Nuevo Proyecto',
    presupuestos_titulo: 'Presupuestos',
    nuevo_presupuesto: 'Nuevo Presupuesto',
    seguimientos_titulo: 'Seguimientos Comercial',
    pipeline_titulo: 'Pipeline Kanban',
    insights_titulo: 'Insights y Métricas Comercial',

    // Contabilidad & Recibos
    gastos_titulo: 'Registro de Gastos',
    nuevo_gasto: 'Nuevo Gasto',
    ingresos_titulo: 'Registro de Ingresos',
    nuevo_ingreso: 'Nuevo Ingreso',
    recuento_diario_titulo: 'Recuento Diario de Caja',
    cierre_caja: 'Cierre de Caja',
    caja_inicial: 'Caja Inicial',
    desfase: 'Desfase',
    mi_liquidacion_titulo: 'Liquidación de Artista',
    liq_estudio_titulo: 'Liquidación de Estudio',
    recibos_titulo: 'Recibos y Facturas',
    generar_recibo: 'Generar Recibo',

    // Configuración & Auth
    configuracion_titulo: 'Configuración del Estudio',
    datos_estudio: 'Datos del Estudio',
    metodos_pago: 'Métodos de Pago',
    notificaciones_config: 'Notificaciones y Alertas',
    iniciar_sesion: 'Iniciar Sesión',
    registrarse: 'Registrarse',
    contrasena: 'Contraseña',

    // Pestañas y campos de Configuración
    tab_estudio: 'Información del estudio',
    tab_regional: 'Ajustes Regionales (US / ES)',
    tab_servicios: 'Servicios',
    tab_horarios: 'Horarios',
    tab_festivos: 'Días festivos',
    tab_facturacion: 'Facturación',
    tab_comunicaciones: 'Comunicaciones',
    tab_calendario: 'Calendario',
    tab_politica: 'Política',
    tab_personalizacion: 'Personalización',

    info_estudio_titulo: 'Información del estudio',
    nombre_estudio: 'Nombre del estudio',
    cif_nif: 'CIF / NIF / Tax ID',
    direccion: 'Dirección',
    codigo_postal: 'Código Postal',
    localidad: 'Localidad',
    provincia: 'Provincia',
    email: 'Email',
    telefono: 'Teléfono',
    codigo_higienico: 'Código Higiénico Sanitario',
    instagram_hint: 'Ej: @mi_estudio',

    config_regional_titulo: 'Configuración Regional e Internacionalización',
    config_regional_sub: 'Adapta KuroIchi al mercado de España (EUR, 24h, DD/MM/YYYY) o Estados Unidos (USD, 12h AM/PM, MM/DD/YYYY, Sales Tax, Tipping).',
    pais_mercado: 'País / Mercado Principal',
    moneda_principal: 'Moneda Principal',
    simbolo_moneda: 'Símbolo de Moneda',
    formato_fecha: 'Formato de Fecha',
    formato_hora: 'Formato de Hora',
    impuesto_defecto: 'Impuesto por Defecto (%)',
    nombre_impuesto: 'Nombre del Impuesto',
    propina_tpv: 'Permitir Propinas en TPV',
    propina_opciones: 'Opciones de Propina Sugerida (%)',

    servicios_titulo: 'Servicios Ofrecidos',
    servicios_sub: 'Gestiona los tipos de servicios disponibles en tu estudio.',
    duracion_defecto: 'Duración por defecto (min)',
    precio_base: 'Precio Base',

    horarios_titulo: 'Horarios de Apertura',
    abierto: 'Abierto',
    cerrado: 'Cerrado',
    apertura: 'Apertura',
    cierre: 'Cierre',
    festivos_titulo: 'Días Festivos',
    anadir_festivo: 'Añadir Día Festivo',
    descripcion_festivo: 'Descripción',

    facturacion_titulo: 'Configuración de Facturación',
    serie_factura: 'Serie / Prefijo de Factura',
    secuencia_factura: 'Próximo Número de Factura',
    reiniciar_secuencia: 'Reiniciar Secuencia',
    nota_pie_factura: 'Nota al Pie de Factura',

    comunicaciones_config_titulo: 'Integraciones y Comunicaciones',
    remitente_email: 'Nombre Remitente Email',
    whatsapp_api: 'Plantilla WhatsApp',

    calendario_config_titulo: 'Ajustes del Calendario',
    intervalo_minutos: 'Intervalo de tiempo (min)',
    mostrar_fines_semana: 'Mostrar Fines de Semana',
    politica_titulo: 'Política y Consentimientos',
    texto_politica_cancelacion: 'Política de Cancelación',
    deposito_politica: 'Política de Depósito / Señal',

    personalizacion_titulo: 'Personalización Visual & Marca',
    logotipo_estudio: 'Logotipo del Estudio',
    subir_logo: 'Subir Logotipo',
    tema_visual: 'Tema Visual',
    modo_oscuro: 'Modo Oscuro',
    modo_claro: 'Modo Claro',

    // Textos comunes
    nuevo: 'Nuevo',
    guardar: 'Guardar',
    guardando: 'Guardando...',
    crear: 'Crear',
    actualizar: 'Actualizar',
    cancelar: 'Cancelar',
    editar: 'Editar',
    eliminar: 'Eliminar',
    buscar: 'Buscar...',
    acciones: 'Acciones',
    estado: 'Estado',
    fecha: 'Fecha',
    cliente: 'Cliente',
    artista: 'Artista',
    total: 'Total',
    idioma: 'Idioma',
    filtros: 'Filtros',
    exportar: 'Exportar',
    limpiar: 'Limpiar',
    nombre: 'Nombre',
    cargando: 'Cargando...',
    detalles: 'Detalles',
  },
  en: {
    // Navigation Categories
    gestion: 'Management',
    comercial: 'Sales & CRM',
    inventario: 'Inventory',
    contabilidad: 'Finance & Payroll',

    // Menu Items
    dashboard: 'Dashboard',
    alertas: 'Alerts',
    calendario: 'Calendar',
    clientes: 'Clients',
    ventas: 'Sales (POS)',
    consentimientos: 'Waivers & Consent',
    cabinas: 'Booths & Rental',
    empleados: 'Staff & Artists',
    comunicaciones: 'Communications',
    leads: 'Leads (Inquiries)',
    proyectos: 'Projects',
    presupuestos: 'Quotes',
    seguimientos: 'Follow-ups',
    pipeline: 'Pipeline (Kanban)',
    insights: 'Sales Insights',
    tintas: 'Inks',
    agujas: 'Needles',
    piercing: 'Piercing',
    materiales: 'Supplies',
    estadisticas: 'Statistics',
    gastos: 'Expenses',
    ingresos: 'Revenue',
    recuento_diario: 'Daily Audit',
    mi_liquidacion: 'My Settlement',
    liq_estudio: 'Studio Payouts',
    recibos: 'Receipts',
    configuracion: 'Settings',
    cerrar_sesion: 'Log Out',
    panel_superadmin: 'SuperAdmin Panel',

    // Dashboard
    buenos_dias: 'Good morning',
    buenas_tardes: 'Good afternoon',
    buenas_noches: 'Good evening',
    accesos_rapidos: 'Quick Access',
    citas_de_hoy: "Today's Appointments",
    ventas_del_mes: 'Monthly Sales',
    gastos_del_mes: 'Monthly Expenses',
    beneficio_del_mes: 'Monthly Profit',
    pendientes: 'Pending',
    alertas_pendientes: 'alerts',
    leads_activos: 'Active Leads',
    en_seguimiento: 'In follow-up',
    proyectos_diseno: 'Projects',
    en_diseno: 'In design / progress',
    presupuestos_aceptados: 'Quotes',
    aceptados: 'Accepted',
    conversion_crm: 'CRM Conversion',
    leads_a_clientes: 'Leads to Clients',
    nueva_cita: 'New Appointment',
    programa_calendario: 'Schedule on calendar',
    anadir_cliente: 'Add Client',
    registra_perfil: 'Register new profile',
    ver_inventario: 'View Inventory',
    consulta_productos: 'Browse products',
    ajusta_estudio: 'Configure studio',
    ir: 'Go →',
    no_hay_citas_hoy: 'No appointments scheduled for today',
    stock_bajo_en: 'Low stock on',
    con_no_shows: 'with 3+ no-shows',
    ausencias_semana: 'Absences this week',

    // Clientes
    clientes_titulo: 'Clients',
    nuevo_cliente: 'New Client',
    duplicados: 'Duplicates',
    buscar_cliente_placeholder: 'Search by name, last name or email...',
    todos: 'All',
    conflictivos: '⚠ Problematic',
    flexibles: 'Flexible',
    sin_resultados: 'No results found',
    no_hay_clientes: 'No registered clients',
    primer_apellido: 'First Last Name',
    segundo_apellido: 'Second Last Name',
    fecha_nacimiento: 'Date of Birth',
    sexo: 'Gender',

    // Calendario & Citas
    calendario_titulo: 'Appointments Calendar',
    mes: 'Month',
    semana: 'Week',
    dia: 'Day',
    hoy: 'Today',

    // TPV & Sales
    ventas_tpv_titulo: 'Point of Sale (POS)',
    nueva_venta: 'New Sale',
    cobrar: 'Checkout',
    ticket: 'Receipt',
    carrito_vacio: 'Cart is empty',
    subtotal: 'Subtotal',
    descuento: 'Discount',
    metodo_pago: 'Payment Method',
    efectivo: 'Cash',
    tarjeta: 'Credit Card',
    bizum: 'Bizum / Instant Pay',
    imprimir_ticket: 'Print Receipt',
    finalizar_venta: 'Complete Sale',

    // Inventory (Inks, Needles, Piercing, Supplies)
    tintas_titulo: 'Inks Management',
    agujas_titulo: 'Needles & Cartridges',
    piercing_titulo: 'Body Jewelry & Piercing',
    materiales_titulo: 'Supplies & Materials',
    stock_actual: 'Current Stock',
    stock_minimo: 'Minimum Stock',
    lote: 'Batch / Lot',
    caducidad: 'Expiration Date',
    proveedor: 'Supplier',
    precio_compra: 'Cost Price',
    precio_venta: 'Retail Price',
    marca: 'Brand',
    modelo: 'Model',
    tipo: 'Type',

    // Booths & Staff
    cabinas_titulo: 'Booths & Workspaces',
    nueva_cabina: 'New Booth',
    empleados_titulo: 'Staff & Artists Management',
    nuevo_empleado: 'New Staff Member',
    comision: 'Commission (%)',
    especialidad: 'Specialty',

    // CRM
    leads_titulo: 'Leads Management',
    nuevo_lead: 'New Lead',
    proyectos_titulo: 'Design Projects',
    nuevo_proyecto: 'New Project',
    presupuestos_titulo: 'Quotes & Estimates',
    nuevo_presupuesto: 'New Quote',
    seguimientos_titulo: 'Sales Follow-ups',
    pipeline_titulo: 'Kanban Pipeline',
    insights_titulo: 'Sales Insights & Metrics',

    // Accounting & Receipts
    gastos_titulo: 'Expenses Log',
    nuevo_gasto: 'New Expense',
    ingresos_titulo: 'Revenue Log',
    nuevo_ingreso: 'New Income',
    recuento_diario_titulo: 'Daily Cash Audit',
    cierre_caja: 'Cash Closeout',
    caja_inicial: 'Opening Cash',
    desfase: 'Discrepancy',
    mi_liquidacion_titulo: 'Artist Settlement',
    liq_estudio_titulo: 'Studio Payouts',
    recibos_titulo: 'Receipts & Invoices',
    generar_recibo: 'Generate Receipt',

    // Settings & Auth
    configuracion_titulo: 'Studio Settings',
    datos_estudio: 'Studio Information',
    metodos_pago: 'Payment Options',
    notificaciones_config: 'Notifications & Alerts',
    iniciar_sesion: 'Log In',
    registrarse: 'Sign Up',
    contrasena: 'Password',

    // Configuration Tabs & Fields
    tab_estudio: 'Studio Information',
    tab_regional: 'Regional Settings (US / ES)',
    tab_servicios: 'Services',
    tab_horarios: 'Business Hours',
    tab_festivos: 'Holidays',
    tab_facturacion: 'Billing & Invoicing',
    tab_comunicaciones: 'Communications',
    tab_calendario: 'Calendar Settings',
    tab_politica: 'Terms & Policies',
    tab_personalizacion: 'Customization',

    info_estudio_titulo: 'Studio Information',
    nombre_estudio: 'Studio Name',
    cif_nif: 'Tax ID / EIN',
    direccion: 'Address',
    codigo_postal: 'Zip / Postal Code',
    localidad: 'City / Town',
    provincia: 'State / Province',
    email: 'Email',
    telefono: 'Phone Number',
    codigo_higienico: 'Health & Sanitation License Code',
    instagram_hint: 'Ex: @my_studio',

    config_regional_titulo: 'Regional & Localization Settings',
    config_regional_sub: 'Adapt KuroIchi for European (EUR, 24h, DD/MM/YYYY) or US markets (USD, 12h AM/PM, MM/DD/YYYY, Sales Tax, Tipping).',
    pais_mercado: 'Primary Market / Country',
    moneda_principal: 'Primary Currency',
    simbolo_moneda: 'Currency Symbol',
    formato_fecha: 'Date Format',
    formato_hora: 'Time Format',
    impuesto_defecto: 'Default Tax Rate (%)',
    nombre_impuesto: 'Tax Name',
    propina_tpv: 'Enable Tipping on POS',
    propina_opciones: 'Suggested Tip Options (%)',

    servicios_titulo: 'Services Offered',
    servicios_sub: 'Manage service offerings available at your studio.',
    duracion_defecto: 'Default Duration (mins)',
    precio_base: 'Base Price',

    horarios_titulo: 'Business Hours',
    abierto: 'Open',
    cerrado: 'Closed',
    apertura: 'Opening Time',
    cierre: 'Closing Time',
    festivos_titulo: 'Holidays & Studio Closures',
    anadir_festivo: 'Add Holiday',
    descripcion_festivo: 'Description',

    facturacion_titulo: 'Billing & Invoice Settings',
    serie_factura: 'Invoice Series / Prefix',
    secuencia_factura: 'Next Invoice Number',
    reiniciar_secuencia: 'Reset Sequence',
    nota_pie_factura: 'Invoice Footer Note',

    comunicaciones_config_titulo: 'Communication & Integration Settings',
    remitente_email: 'Email Sender Name',
    whatsapp_api: 'WhatsApp Message Template',

    calendario_config_titulo: 'Calendar Settings',
    intervalo_minutos: 'Time Slot Interval (mins)',
    mostrar_fines_semana: 'Show Weekends',
    politica_titulo: 'Terms & Policies',
    texto_politica_cancelacion: 'Cancellation Policy Text',
    deposito_politica: 'Deposit & Retainer Policy',

    personalizacion_titulo: 'Branding & Visual Theme',
    logotipo_estudio: 'Studio Logo',
    subir_logo: 'Upload Logo',
    tema_visual: 'Visual Theme',
    modo_oscuro: 'Dark Mode',
    modo_claro: 'Light Mode',

    // Common Text
    nuevo: 'New',
    guardar: 'Save',
    guardando: 'Saving...',
    crear: 'Create',
    actualizar: 'Update',
    cancelar: 'Cancel',
    editar: 'Edit',
    eliminar: 'Delete',
    buscar: 'Search...',
    acciones: 'Actions',
    estado: 'Status',
    fecha: 'Date',
    cliente: 'Client',
    artista: 'Artist',
    total: 'Total',
    idioma: 'Language',
    filtros: 'Filters',
    exportar: 'Export',
    limpiar: 'Clear',
    nombre: 'Name',
    cargando: 'Loading...',
    detalles: 'Details',
  }
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => localStorage.getItem('kuroichi_lang') || 'es');

  const changeLanguage = (newLang) => {
    setLang(newLang);
    localStorage.setItem('kuroichi_lang', newLang);
  };

  const t = (key) => {
    return translations[lang]?.[key] || translations['es']?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang: changeLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
