import React, { createContext, useState, useContext } from 'react';

const translations = {
  es: {
    // Categorías de Navegación
    gestion: 'Gestión',
    comercial: 'Comercial',
    inventario: 'Inventario',
    contabilidad: 'Contabilidad',

    // Elementos del menú
    dashboard: 'Dashboard',
    alertas: 'Alertas',
    calendario: 'Calendario',
    clientes: 'Clientes',
    ventas: 'Ventas (TPV)',
    consentimientos: 'Consentimientos',
    cabinas: 'Cabinas & Alquileres',
    empleados: 'Empleados',
    comunicaciones: 'Comunicaciones',
    leads: 'Leads',
    proyectos: 'Proyectos',
    presupuestos: 'Presupuestos',
    seguimientos: 'Seguimientos',
    pipeline: 'Pipeline (Kanban)',
    insights: 'Insights Comercial',
    tintas: 'Tintas',
    agujas: 'Agujas',
    piercing: 'Piercing',
    materiales: 'Materiales',
    estadisticas: 'Estadísticas',
    gastos: 'Gastos',
    ingresos: 'Ingresos',
    recuento_diario: 'Recuento Diario',
    mi_liquidacion: 'Mi Liquidación',
    liq_estudio: 'Liq. Estudio',
    recibos: 'Recibos',
    configuracion: 'Configuración',
    cerrar_sesion: 'Cerrar sesión',
    panel_superadmin: 'Panel SuperAdmin',

    // Landing Page
    landing_herramientas: 'HERRAMIENTAS',
    landing_vista: 'VISTA SOFTWARE',
    landing_precios: 'PRECIOS',
    landing_contacto: 'CONTACTO',
    landing_acceder: 'Acceder',
    landing_prueba_gratis: 'Pruébalo Gratis',
    landing_badge: 'Software de Gestión para Estudios de Tatuaje & Piercing',
    landing_hero_title1: 'Gobierna tu estudio,',
    landing_hero_title2: 'domina el arte de la tinta',
    landing_hero_sub: 'Gestión completa de citas, agenda iCal, consentimientos informados con Firma Digital en Tablet, TPV, CRM Kanban y alquiler de cabinas.',
    landing_hero_cta: 'Prueba KuroIchi PRO 14 Días Gratis',
    landing_trust: 'Ya confían en KuroIchi:',

    // Dashboard
    buenos_dias: 'Buenos días',
    buenas_tardes: 'Buenas tardes',
    buenas_noches: 'Buenas noches',
    accesos_rapidos: 'Accesos Rápidos',
    citas_de_hoy: 'Citas de hoy',
    ventas_del_mes: 'Ventas del mes',
    gastos_del_mes: 'Gastos del mes',
    beneficio_del_mes: 'Beneficio del mes',
    pendientes: 'Pendientes',
    alertas_pendientes: 'alertas',
    leads_activos: 'Leads Activos',
    en_seguimiento: 'En seguimiento',
    proyectos_diseno: 'Proyectos',
    en_diseno: 'En diseño / curso',
    presupuestos_aceptados: 'Presupuestos',
    aceptados: 'Aceptados',
    conversion_crm: 'Conversión CRM',
    leads_a_clientes: 'Leads a Clientes',
    nueva_cita: 'Nueva Cita',
    programa_calendario: 'Programa en el calendario',
    anadir_cliente: 'Añadir Cliente',
    registra_perfil: 'Registra un nuevo perfil',
    ver_inventario: 'Ver Inventario',
    consulta_productos: 'Consulta tus productos',
    ajusta_estudio: 'Ajusta tu estudio',
    ir: 'Ir →',
    no_hay_citas_hoy: 'No hay citas programadas para hoy',
    stock_bajo_en: 'Stock bajo en',
    con_no_shows: 'con 3+ no-shows',
    ausencias_semana: 'Ausencias esta semana',

    // Clientes
    clientes_titulo: 'Clientes',
    nuevo_cliente: 'Nuevo cliente',
    duplicados: 'Duplicados',
    buscar_cliente_placeholder: 'Buscar por nombre, apellidos o email...',
    todos: 'Todos',
    conflictivos: '⚠ Conflictivos',
    flexibles: 'Flexibles',
    sin_resultados: 'No se encontraron resultados',
    no_hay_clientes: 'No hay clientes registrados',
    primer_apellido: 'Primer apellido',
    segundo_apellido: 'Segundo apellido',
    fecha_nacimiento: 'Fecha de nacimiento',
    sexo: 'Sexo',

    // Calendario & Citas
    calendario_titulo: 'Calendario de Citas',
    mes: 'Mes',
    semana: 'Semana',
    dia: 'Día',
    hoy: 'Hoy',

    // TPV & Ventas
    ventas_tpv_titulo: 'Terminal Punto de Venta (TPV)',
    nueva_venta: 'Nueva Venta',
    cobrar: 'Cobrar',
    ticket: 'Ticket',
    carrito_vacio: 'El carrito está vacío',
    subtotal: 'Subtotal',
    descuento: 'Descuento',
    metodo_pago: 'Método de Pago',
    efectivo: 'Efectivo',
    tarjeta: 'Tarjeta',
    bizum: 'Bizum',
    imprimir_ticket: 'Imprimir Ticket',
    finalizar_venta: 'Finalizar Venta',

    // Inventario
    tintas_titulo: 'Gestión de Tintas',
    agujas_titulo: 'Gestión de Agujas y Cartuchos',
    piercing_titulo: 'Gestión de Piercing y Joyería',
    materiales_titulo: 'Materiales e Insumos',
    stock_actual: 'Stock Actual',
    stock_minimo: 'Stock Mínimo',
    lote: 'Lote',
    caducidad: 'Fecha de Caducidad',
    proveedor: 'Proveedor',
    precio_compra: 'Precio Compra',
    precio_venta: 'Precio Venta',
    marca: 'Marca',
    modelo: 'Modelo',
    tipo: 'Tipo',

    // Cabinas & Empleados
    cabinas_titulo: 'Cabinas y Espacios de Trabajo',
    nueva_cabina: 'Nueva Cabina',
    empleados_titulo: 'Gestión de Empleados y Artistas',
    nuevo_empleado: 'Nuevo Empleado',
    comision: 'Comisión (%)',
    especialidad: 'Especialidad',

    // CRM
    leads_titulo: 'Gestión de Leads',
    nuevo_lead: 'Nuevo Lead',
    proyectos_titulo: 'Proyectos de Diseño',
    nuevo_proyecto: 'Nuevo Proyecto',
    presupuestos_titulo: 'Presupuestos',
    nuevo_presupuesto: 'Nuevo Presupuesto',
    seguimientos_titulo: 'Seguimientos Comercial',
    pipeline_titulo: 'Pipeline Kanban',
    insights_titulo: 'Insights y Métricas Comercial',

    // Contabilidad & Recibos
    gastos_titulo: 'Registro de Gastos',
    nuevo_gasto: 'Nuevo Gasto',
    ingresos_titulo: 'Registro de Ingresos',
    nuevo_ingreso: 'Nuevo Ingreso',
    recuento_diario_titulo: 'Recuento Diario de Caja',
    cierre_caja: 'Cierre de Caja',
    caja_inicial: 'Caja Inicial',
    desfase: 'Desfase',
    mi_liquidacion_titulo: 'Liquidación de Artista',
    liq_estudio_titulo: 'Liquidación de Estudio',
    recibos_titulo: 'Recibos y Facturas',
    generar_recibo: 'Generar Recibo',

    // Configuración General
    configuracion_titulo: 'Configuración del Estudio',
    datos_estudio: 'Datos del Estudio',
    metodos_pago: 'Métodos de Pago',
    notificaciones_config: 'Notificaciones y Alertas',
    iniciar_sesion: 'Iniciar Sesión',
    registrarse: 'Registrarse',
    contrasena: 'Contraseña',

    tab_estudio: 'Información del estudio',
    tab_regional: 'Ajustes Regionales (US / ES)',
    tab_servicios: 'Servicios',
    tab_horarios: 'Horarios',
    tab_festivos: 'Días festivos',
    tab_facturacion: 'Facturación',
    tab_comunicaciones: 'Comunicaciones',
    tab_calendario: 'Calendario',
    tab_politica: 'Política',
    tab_personalizacion: 'Personalización',

    info_estudio_titulo: 'Información del estudio',
    nombre_estudio: 'Nombre del estudio',
    cif_nif: 'CIF / NIF / Tax ID',
    direccion: 'Dirección',
    codigo_postal: 'Código Postal',
    localidad: 'Localidad',
    provincia: 'Provincia',
    email: 'Email',
    telefono: 'Teléfono',
    codigo_higienico: 'Código Higiénico Sanitario',
    instagram_hint: 'Ej: @mi_estudio',

    config_regional_titulo: 'Configuración Regional e Internacionalización',
    config_regional_sub: 'Adapta KuroIchi al mercado de España (EUR, 24h, DD/MM/YYYY) o Estados Unidos (USD, 12h AM/PM, MM/DD/YYYY, Sales Tax, Tipping).',
    pais_mercado: 'País / Mercado Principal',
    moneda_principal: 'Moneda Principal',
    simbolo_moneda: 'Símbolo de Moneda',
    formato_fecha: 'Formato de Fecha',
    formato_hora: 'Formato de Hora',
    impuesto_defecto: 'Impuesto por Defecto (%)',
    nombre_impuesto: 'Nombre del Impuesto',
    propina_tpv: 'Permitir Propinas en TPV',
    propina_opciones: 'Opciones de Propina Sugerida (%)',

    servicios_titulo: 'Servicios Ofrecidos',
    servicios_sub: 'Gestiona los tipos de servicios disponibles en tu estudio.',
    duracion_defecto: 'Duración por defecto (min)',
    precio_base: 'Precio Base',

    horarios_titulo: 'Horarios de Apertura',
    abierto: 'Abierto',
    cerrado: 'Cerrado',
    apertura: 'Apertura',
    cierre: 'Cierre',

    festivos_titulo: 'Días Festivos',
    festivos_sub: 'Los días festivos se marcan en rojo en el calendario.',
    fecha_festivo: 'Fecha',
    descripcion_festivo: 'Descripción',
    descripcion_festivo_hint: 'Ej: Día de la Hispanidad, Año Nuevo...',
    anadir: 'Añadir',

    facturacion_titulo: 'Configuración de Facturación',
    iva_defecto_label: 'IVA por defecto (%)',
    iva_defecto_hint: 'Se aplica al crear nuevas facturas',
    comision_estudio_label: 'Comisión clientes del estudio (%)',
    comision_estudio_hint: 'Porcentaje que retiene el estudio de citas sin artista asignado',
    facturas_auto_label: 'Facturas automáticas',
    facturas_auto_hint: 'Genera facturas automáticamente al completar una cita',

    comunicaciones_config_titulo: 'Integraciones y Comunicaciones',
    dni_obligatorio_label: 'DNI obligatorio en consentimientos',
    dni_obligatorio_desc: 'Requiere que el cliente introduzca su DNI al firmar el consentimiento',
    copia_cliente_label: 'Enviar copia del consentimiento al cliente',
    copia_cliente_desc: 'Envía el PDF del consentimiento firmado por email al cliente',
    copia_estudio_label: 'Enviar copia del consentimiento al estudio',
    copia_estudio_desc: 'Envía también al email del estudio una copia del consentimiento firmado',
    enlace_firma_label: 'Incluir enlace de firma en el email de cita',
    enlace_firma_desc: 'Añade un enlace al consentimiento en el email de confirmación de cita',

    calendario_config_titulo: 'Ajustes del Calendario',
    citas_nueva_pestana_label: 'Abrir citas en nueva pestaña',
    citas_nueva_pestana_desc: 'Al hacer clic en una cita del calendario se abre en una nueva pestaña del navegador',
    texto_blanco_label: 'Forzar texto blanco en eventos',
    texto_blanco_desc: 'Hace que el texto de los eventos del calendario sea siempre blanco, independientemente del color del artista',
    intensidad_color_label: 'Intensidad color artistas',
    intensidad_color_desc: 'Controla la opacidad del color asignado a cada artista en el calendario',

    politica_titulo: 'Política y Consentimientos',
    texto_politica_cancelacion: 'Política de Cancelación',
    deposito_politica: 'Política de Depósito / Señal',

    personalizacion_titulo: 'Personalización Visual & Marca',

    // Subpestañas de Personalización
    subtab_panel: 'Panel',
    subtab_facturas: 'Facturas',
    subtab_tickets: 'Tickets',
    subtab_consentimientos: 'Consentimientos',
    subtab_whatsapp: 'WhatsApp',
    subtab_correo: 'Correo',

    person_panel_titulo: 'Personalización del Panel',
    person_panel_sub: 'Ajusta los colores, tipografía y logotipo para adaptar la plataforma a la imagen de tu estudio.',
    skins_titulo: 'Skins Predefinidas (Estilos)',
    color_principal: 'Color Principal (Acento)',
    color_principal_hint: 'Color de botones y elementos activos',
    color_fondo: 'Color de Fondo Principal',
    color_fondo_hint: 'Color de fondo de la aplicación',
    color_superficie: 'Color de Fondo Secundario',
    color_superficie_hint: 'Color de los paneles y tarjetas',
    tipografia: 'Tipografía Principal',
    tipografia_hint: 'Fuente usada en todo el panel',
    tamano_letra: 'Tamaño de Letra Base',
    tamano_letra_hint: 'Tamaño por defecto (ej. 14px o 16px)',
    logo_estudio: 'Logotipo del Estudio',
    sin_logo: 'Sin logo',
    subir_logo_hint: 'Sube una imagen (PNG, JPG) para usarla como logotipo principal. Tamaño máximo recomendado: 2MB.',

    person_facturas_titulo: 'Personalización de Facturas',
    person_facturas_sub: 'Configura los datos fiscales y visuales que aparecerán en las facturas y documentos tamaño A4.',
    nombre_fiscal: 'Nombre Fiscal / Empresa',
    direccion_completa: 'Dirección Completa',
    datos_contacto: 'Datos de Contacto',
    anio_fiscal: 'Año Fiscal (Opcional)',
    anio_fiscal_hint: 'Fuerza un año para el prefijo de factura. Déjalo en blanco para usar el año actual.',
    reiniciar_contador: 'Reiniciar Contador de Facturas',
    reiniciar_contador_hint: 'Atención: Modifica el número de la siguiente factura a emitir.',
    proximo_numero: 'Próximo número...',
    reiniciar: 'Reiniciar',
    texto_legal_factura: 'Texto Legal / Pie de Factura',
    logo_factura: 'Logotipo para Facturas (Opcional)',
    logo_factura_general: 'Usará el logo general',
    logo_factura_hint: 'Sube una imagen específica (ideal fondo transparente/blanco) para las facturas y tickets impresos.',

    person_tickets_titulo: 'Personalización de Tickets (80mm)',
    person_tickets_sub: 'Configura el diseño y opciones de impresión para los tickets de caja y recibos impresos térmicamente.',
    diseno_ticket: 'Diseño del Ticket',
    ticket_encabezado: 'Encabezado (Inicio de página)',
    ticket_pie: 'Pie de página',
    prefijo_ticket: 'Prefijo Núm. Ticket',
    longitud_minima: 'Long. Mínima Número',
    desactivar_impresion_auto: 'Desactivar Impresión Automática',
    activar_ticket_email: 'Activar Tickets Digitales por Email',

    person_consent_titulo: 'Consentimientos Informados',
    person_consent_sub: 'Personaliza los textos legales, cuidados y curas que se incluirán en el documento de consentimiento.',
    ver_vista_previa: 'Ver Vista Previa',
    instrucciones_curas: 'Instrucciones de Curas',
    instrucciones_curas_hint: 'Explica paso a paso cómo realizar las curas. Si se deja en blanco se usará la plantilla estándar.',
    cuidados_generales: 'Instrucciones Generales de Cuidados',
    cuidados_generales_hint: 'Recomendaciones generales y cosas a evitar (sol, piscina, playa, etc.).',
    proteccion_datos_rgpd: 'Cláusula de Protección de Datos (RGPD)',
    proteccion_datos_rgpd_hint: 'Texto legal específico sobre el tratamiento de los datos personales y médicos del cliente.',

    person_whatsapp_titulo: 'Mensajes de WhatsApp',
    person_whatsapp_sub: 'Configura la plantilla para los mensajes de WhatsApp. Puedes usar las variables: [CLIENTE], [FECHA], [HORA], [SERVICIO], que se rellenarán automáticamente al contactar.',
    plantilla_whatsapp: 'Plantilla de Mensaje (Recordatorio/Cita)',

    person_correo_titulo: 'Notificaciones por Correo',
    person_correo_sub: 'Configura el diseño del pie de página y los textos legales (RGPD) que se incluirán en todos los correos electrónicos enviados.',
    correo_pie_firma: 'Pie de Página (Firma / Despedida)',
    correo_pie_firma_hint: 'Texto que aparecerá al final del cuerpo del correo.',
    correo_aviso_legal: 'Aviso Legal y Protección de Datos (RGPD)',
    correo_aviso_legal_hint: 'Este texto aparecerá en letra pequeña al fondo del correo electrónico.',

    // Textos comunes
    nuevo: 'Nuevo',
    guardar: 'Guardar',
    guardando: 'Guardando...',
    crear: 'Crear',
    actualizar: 'Actualizar',
    cancelar: 'Cancelar',
    editar: 'Editar',
    eliminar: 'Eliminar',
    buscar: 'Buscar...',
    acciones: 'Acciones',
    estado: 'Estado',
    fecha: 'Fecha',
    cliente: 'Cliente',
    artista: 'Artista',
    total: 'Total',
    idioma: 'Idioma',
    filtros: 'Filtros',
    exportar: 'Exportar',
    limpiar: 'Limpiar',
    nombre: 'Nombre',
    cargando: 'Cargando...',
    detalles: 'Detalles',
  },
  en: {
    // Navigation Categories
    gestion: 'Management',
    comercial: 'Sales & CRM',
    inventario: 'Inventory',
    contabilidad: 'Finance & Payroll',

    // Menu Items
    dashboard: 'Dashboard',
    alertas: 'Alerts',
    calendario: 'Calendar',
    clientes: 'Clients',
    ventas: 'Sales (POS)',
    consentimientos: 'Waivers & Consent',
    cabinas: 'Booths & Rental',
    empleados: 'Staff & Artists',
    comunicaciones: 'Communications',
    leads: 'Leads (Inquiries)',
    proyectos: 'Projects',
    presupuestos: 'Quotes',
    seguimientos: 'Follow-ups',
    pipeline: 'Pipeline (Kanban)',
    insights: 'Sales Insights',
    tintas: 'Inks',
    agujas: 'Needles',
    piercing: 'Piercing',
    materiales: 'Supplies',
    estadisticas: 'Statistics',
    gastos: 'Expenses',
    ingresos: 'Revenue',
    recuento_diario: 'Daily Audit',
    mi_liquidacion: 'My Settlement',
    liq_estudio: 'Studio Payouts',
    recibos: 'Receipts',
    configuracion: 'Settings',
    cerrar_sesion: 'Log Out',
    panel_superadmin: 'SuperAdmin Panel',

    // Landing Page
    landing_herramientas: 'FEATURES',
    landing_vista: 'APP PREVIEW',
    landing_precios: 'PRICING',
    landing_contacto: 'CONTACT',
    landing_acceder: 'Log In',
    landing_prueba_gratis: 'Try Free',
    landing_badge: 'Tattoo & Piercing Studio Management Software',
    landing_hero_title1: 'Govern your studio,',
    landing_hero_title2: 'master the art of ink',
    landing_hero_sub: 'Complete appointment management, iCal sync, Digital Signature waivers on Tablet, POS, Kanban CRM, and booth rentals.',
    landing_hero_cta: 'Try KuroIchi PRO 14 Days Free',
    landing_trust: 'Trusted by leading studios:',

    // Dashboard
    buenos_dias: 'Good morning',
    buenas_tardes: 'Good afternoon',
    buenas_noches: 'Good evening',
    accesos_rapidos: 'Quick Access',
    citas_de_hoy: "Today's Appointments",
    ventas_del_mes: 'Monthly Sales',
    gastos_del_mes: 'Monthly Expenses',
    beneficio_del_mes: 'Monthly Profit',
    pendientes: 'Pending',
    alertas_pendientes: 'alerts',
    leads_activos: 'Active Leads',
    en_seguimiento: 'In follow-up',
    proyectos_diseno: 'Projects',
    en_diseno: 'In design / progress',
    presupuestos_aceptados: 'Quotes',
    aceptados: 'Accepted',
    conversion_crm: 'CRM Conversion',
    leads_a_clientes: 'Leads to Clients',
    nueva_cita: 'New Appointment',
    programa_calendario: 'Schedule on calendar',
    anadir_cliente: 'Add Client',
    registra_perfil: 'Register new profile',
    ver_inventario: 'View Inventory',
    consulta_productos: 'Browse products',
    ajusta_estudio: 'Configure studio',
    ir: 'Go →',
    no_hay_citas_hoy: 'No appointments scheduled for today',
    stock_bajo_en: 'Low stock on',
    con_no_shows: 'with 3+ no-shows',
    ausencias_semana: 'Absences this week',

    // Clientes
    clientes_titulo: 'Clients',
    nuevo_cliente: 'New Client',
    duplicados: 'Duplicates',
    buscar_cliente_placeholder: 'Search by name, last name or email...',
    todos: 'All',
    conflictivos: '⚠ Problematic',
    flexibles: 'Flexible',
    sin_resultados: 'No results found',
    no_hay_clientes: 'No registered clients',
    primer_apellido: 'First Last Name',
    segundo_apellido: 'Second Last Name',
    fecha_nacimiento: 'Date of Birth',
    sexo: 'Gender',

    // Calendario & Citas
    calendario_titulo: 'Appointments Calendar',
    mes: 'Month',
    semana: 'Week',
    dia: 'Day',
    hoy: 'Today',

    // TPV & Sales
    ventas_tpv_titulo: 'Point of Sale (POS)',
    nueva_venta: 'New Sale',
    cobrar: 'Checkout',
    ticket: 'Receipt',
    carrito_vacio: 'Cart is empty',
    subtotal: 'Subtotal',
    descuento: 'Discount',
    metodo_pago: 'Payment Method',
    efectivo: 'Cash',
    tarjeta: 'Credit Card',
    bizum: 'Bizum / Instant Pay',
    imprimir_ticket: 'Print Receipt',
    finalizar_venta: 'Complete Sale',

    // Inventory
    tintas_titulo: 'Inks Management',
    agujas_titulo: 'Needles & Cartridges',
    piercing_titulo: 'Body Jewelry & Piercing',
    materiales_titulo: 'Supplies & Materials',
    stock_actual: 'Current Stock',
    stock_minimo: 'Minimum Stock',
    lote: 'Batch / Lot',
    caducidad: 'Expiration Date',
    proveedor: 'Supplier',
    precio_compra: 'Cost Price',
    precio_venta: 'Retail Price',
    marca: 'Brand',
    modelo: 'Model',
    tipo: 'Type',

    // Booths & Staff
    cabinas_titulo: 'Booths & Workspaces',
    nueva_cabina: 'New Booth',
    empleados_titulo: 'Staff & Artists Management',
    nuevo_empleado: 'New Staff Member',
    comision: 'Commission (%)',
    especialidad: 'Specialty',

    // CRM
    leads_titulo: 'Leads Management',
    nuevo_lead: 'New Lead',
    proyectos_titulo: 'Design Projects',
    nuevo_proyecto: 'New Project',
    presupuestos_titulo: 'Quotes & Estimates',
    nuevo_presupuesto: 'New Quote',
    seguimientos_titulo: 'Sales Follow-ups',
    pipeline_titulo: 'Kanban Pipeline',
    insights_titulo: 'Sales Insights & Metrics',

    // Accounting & Receipts
    gastos_titulo: 'Expenses Log',
    nuevo_gasto: 'New Expense',
    ingresos_titulo: 'Revenue Log',
    nuevo_ingreso: 'New Income',
    recuento_diario_titulo: 'Daily Cash Audit',
    cierre_caja: 'Cash Closeout',
    caja_inicial: 'Opening Cash',
    desfase: 'Discrepancy',
    mi_liquidacion_titulo: 'Artist Settlement',
    liq_estudio_titulo: 'Studio Payouts',
    recibos_titulo: 'Receipts & Invoices',
    generar_recibo: 'Generate Receipt',

    // Settings General
    configuracion_titulo: 'Studio Settings',
    datos_estudio: 'Studio Information',
    metodos_pago: 'Payment Options',
    notificaciones_config: 'Notifications & Alerts',
    iniciar_sesion: 'Log In',
    registrarse: 'Sign Up',
    contrasena: 'Password',

    tab_estudio: 'Studio Information',
    tab_regional: 'Regional Settings (US / ES)',
    tab_servicios: 'Services',
    tab_horarios: 'Business Hours',
    tab_festivos: 'Holidays',
    tab_facturacion: 'Billing & Invoicing',
    tab_comunicaciones: 'Communications',
    tab_calendario: 'Calendar Settings',
    tab_politica: 'Terms & Policies',
    tab_personalizacion: 'Customization',

    info_estudio_titulo: 'Studio Information',
    nombre_estudio: 'Studio Name',
    cif_nif: 'Tax ID / EIN',
    direccion: 'Address',
    codigo_postal: 'Zip / Postal Code',
    localidad: 'City / Town',
    provincia: 'State / Province',
    email: 'Email',
    telefono: 'Phone Number',
    codigo_higienico: 'Health & Sanitation License Code',
    instagram_hint: 'Ex: @my_studio',

    config_regional_titulo: 'Regional & Localization Settings',
    config_regional_sub: 'Adapt KuroIchi for European (EUR, 24h, DD/MM/YYYY) or US markets (USD, 12h AM/PM, MM/DD/YYYY, Sales Tax, Tipping).',
    pais_mercado: 'Primary Market / Country',
    moneda_principal: 'Primary Currency',
    simbolo_moneda: 'Currency Symbol',
    formato_fecha: 'Date Format',
    formato_hora: 'Time Format',
    impuesto_defecto: 'Default Tax Rate (%)',
    nombre_impuesto: 'Tax Name',
    propina_tpv: 'Enable Tipping on POS',
    propina_opciones: 'Suggested Tip Options (%)',

    servicios_titulo: 'Services Offered',
    servicios_sub: 'Manage service offerings available at your studio.',
    duracion_defecto: 'Default Duration (mins)',
    precio_base: 'Base Price',

    horarios_titulo: 'Business Hours',
    abierto: 'Open',
    cerrado: 'Closed',
    apertura: 'Opening Time',
    cierre: 'Closing Time',

    festivos_titulo: 'Holidays & Studio Closures',
    festivos_sub: 'Holidays are highlighted in red on the calendar grid.',
    fecha_festivo: 'Date',
    descripcion_festivo: 'Description',
    descripcion_festivo_hint: 'Ex: New Year, Independence Day...',
    anadir: 'Add',

    facturacion_titulo: 'Billing & Invoice Settings',
    iva_defecto_label: 'Default VAT / Tax (%)',
    iva_defecto_hint: 'Applied when generating new invoices',
    comision_estudio_label: 'Studio House Commission (%)',
    comision_estudio_hint: 'Percentage retained by studio for unassigned artist bookings',
    facturas_auto_label: 'Automatic Invoicing',
    facturas_auto_hint: 'Automatically generates invoices upon completing an appointment',

    comunicaciones_config_titulo: 'Communication & Integration Settings',
    dni_obligatorio_label: 'ID / Passport mandatory on consent forms',
    dni_obligatorio_desc: 'Requires client to enter national ID or passport when signing waiver',
    copia_cliente_label: 'Send copy of signed consent form to client',
    copia_cliente_desc: 'Emails signed consent PDF directly to client',
    copia_estudio_label: 'Send copy of signed consent form to studio',
    copia_estudio_desc: 'Sends signed consent PDF copy to studio inbox',
    enlace_firma_label: 'Include waiver signature link in booking email',
    enlace_firma_desc: 'Adds direct waiver signing link to appointment confirmation email',

    calendario_config_titulo: 'Calendar Settings',
    citas_nueva_pestana_label: 'Open appointments in new tab',
    citas_nueva_pestana_desc: 'Clicking a calendar booking opens it in a new browser tab',
    texto_blanco_label: 'Force white text on events',
    texto_blanco_desc: 'Ensures booking text remains white regardless of artist color',
    intensidad_color_label: 'Artist color opacity',
    intensidad_color_desc: 'Controls opacity of assigned artist colors on calendar grid',

    politica_titulo: 'Terms & Policies',
    texto_politica_cancelacion: 'Cancellation Policy Text',
    deposito_politica: 'Deposit & Retainer Policy',

    personalizacion_titulo: 'Branding & Visual Theme',

    // Personalization Subtabs
    subtab_panel: 'Panel & Theme',
    subtab_facturas: 'Invoices',
    subtab_tickets: 'Receipts',
    subtab_consentimientos: 'Consent Waivers',
    subtab_whatsapp: 'WhatsApp',
    subtab_correo: 'Email',

    person_panel_titulo: 'Panel Customization',
    person_panel_sub: 'Adjust colors, typography, and logo to customize the platform to your studio style.',
    skins_titulo: 'Preset Color Skins (Themes)',
    color_principal: 'Primary Accent Color',
    color_principal_hint: 'Color for buttons and active items',
    color_fondo: 'Main Background Color',
    color_fondo_hint: 'Application background color',
    color_superficie: 'Surface / Card Background Color',
    color_superficie_hint: 'Color for cards and panels',
    tipografia: 'Main Typography',
    tipografia_hint: 'Font family used across the panel',
    tamano_letra: 'Base Font Size',
    tamano_letra_hint: 'Default font size (e.g. 14px or 16px)',
    logo_estudio: 'Studio Logo',
    sin_logo: 'No logo',
    subir_logo_hint: 'Upload an image (PNG, JPG) to use as main logo. Recommended max size: 2MB.',

    person_facturas_titulo: 'Invoice Customization',
    person_facturas_sub: 'Configure fiscal details and branding shown on A4 invoices and tax documents.',
    nombre_fiscal: 'Company / Business Name',
    direccion_completa: 'Full Address',
    datos_contacto: 'Contact Details',
    anio_fiscal: 'Fiscal Year (Optional)',
    anio_fiscal_hint: 'Overrides invoice year prefix. Leave empty for current year.',
    reiniciar_contador: 'Reset Invoice Counter',
    reiniciar_contador_hint: 'Warning: Changes the number of the next issued invoice.',
    proximo_numero: 'Next invoice number...',
    reiniciar: 'Reset',
    texto_legal_factura: 'Legal Notice / Invoice Footer',
    logo_factura: 'Invoice Logo (Optional)',
    logo_factura_general: 'Will use general logo',
    logo_factura_hint: 'Upload a specific logo (transparent/white background recommended) for printed invoices and receipts.',

    person_tickets_titulo: 'Receipt Printer Customization (80mm)',
    person_tickets_sub: 'Configure thermal receipt design and printing options for POS receipts.',
    diseno_ticket: 'Receipt Layout',
    ticket_encabezado: 'Header (Top of Receipt)',
    ticket_pie: 'Footer (Bottom of Receipt)',
    prefijo_ticket: 'Receipt Prefix',
    longitud_minima: 'Minimum Digit Count',
    desactivar_impresion_auto: 'Disable Automatic Printing',
    activar_ticket_email: 'Enable Digital Email Receipts',

    person_consent_titulo: 'Informed Consent Waivers',
    person_consent_sub: 'Customize legal disclaimers, care instructions, and aftercare for consent waivers.',
    ver_vista_previa: 'View Preview',
    instrucciones_curas: 'Aftercare Instructions',
    instrucciones_curas_hint: 'Explain step-by-step aftercare. If left empty, standard template will be used.',
    cuidados_generales: 'General Care Recommendations',
    cuidados_generales_hint: 'General recommendations and things to avoid (sun, pool, ocean, etc.).',
    proteccion_datos_rgpd: 'Data Protection & Privacy Notice (GDPR/CCPA)',
    proteccion_datos_rgpd_hint: 'Specific legal clause regarding customer personal and medical data handling.',

    person_whatsapp_titulo: 'WhatsApp Messaging',
    person_whatsapp_sub: 'Configure WhatsApp message template. You can use variables: [CLIENTE], [FECHA], [HORA], [SERVICIO], auto-filled upon outreach.',
    plantilla_whatsapp: 'Message Template (Reminder / Appointment)',

    person_correo_titulo: 'Email Notifications',
    person_correo_sub: 'Configure footer signatures and legal disclaimers included in outgoing emails.',
    correo_pie_firma: 'Footer Signature / Farewell',
    correo_pie_firma_hint: 'Text shown at the bottom of email body.',
    correo_aviso_legal: 'Legal Notice & Data Privacy',
    correo_aviso_legal_hint: 'This text will appear in small print at the footer of sent emails.',

    // Common Text
    nuevo: 'New',
    guardar: 'Save',
    guardando: 'Saving...',
    crear: 'Create',
    actualizar: 'Update',
    cancelar: 'Cancel',
    editar: 'Edit',
    eliminar: 'Delete',
    buscar: 'Search...',
    acciones: 'Actions',
    estado: 'Status',
    fecha: 'Date',
    cliente: 'Client',
    artista: 'Artist',
    total: 'Total',
    idioma: 'Language',
    filtros: 'Filters',
    exportar: 'Export',
    limpiar: 'Clear',
    nombre: 'Name',
    cargando: 'Loading...',
    detalles: 'Details',
  }
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => localStorage.getItem('kuroichi_lang') || 'es');

  const changeLanguage = (newLang) => {
    setLang(newLang);
    localStorage.setItem('kuroichi_lang', newLang);
  };

  const t = (key) => {
    return translations[lang]?.[key] || translations['es']?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang: changeLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
